import React from 'react'
import '../BottomBar.css';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faGithubSquare } from '@fortawesome/free-brands-svg-icons';




const BottomBar = () => {

    return (
        <footer className="footer">
            <div className="waves">
                <div className="wave" id="wave1"></div>
                <div className="wave" id="wave2"></div>
                <div className="wave" id="wave3"></div>
                <div className="wave" id="wave4"></div>
            </div>
            <ul className="social-icon">
                <li className="social-icon__item">
                </li>
            </ul>
            <ul className="menu">
                <li className="menu__item">
                    <a className="social-icon__link" href="https://github.com/grantbrown2/SimpleList">
                        <FontAwesomeIcon icon={faGithubSquare} />
                    </a>
                </li>
                <li className="menu__item">
                    <a className="menu__link" href="/">
                        Home
                    </a>
                </li>
                <li className="menu__item">
                    <a className="menu__link" href="/">
                        About
                    </a>
                </li>
                <li className="menu__item">
                    <a className="menu__link" href="/">
                        Contact
                    </a>
                </li>
            </ul>
            <h4 className='NASA'>Daily Background Generated By NASA'S APOD: <br /> https://data.nasa.gov/Space-Science/Astronomy-Picture-of-the-Day-API/ez2w-t8ua</h4>
        </footer>
    )
}

export default BottomBar